site_name: Cloud-V Docs
nav:
  - Home: index.md
  - Getting Started:
      - Setting up CI/CD on RISC-V: 
        - CI/CD on RISC-V: cicd.md
        - Version Control Systems:
            - Register free GitHub Runner: setting_up_github_runner.md
            - Register free GitLab Runner: setting_up_gitlab_runner.md
        - KernelCI:
            - Getting Access to LAVA: getting_started_lava.md
      - Setting up SSH on RISC-V: sandboxing.md
  - Compute Instance Specifications: compute_instances.md


theme:
  name: material
  logo: doc_images/cloud-v-logo.png
  favicon: doc_images/cloud-v-logo.png
