site_name: RISC-V CI Docs
nav:
- Home: index.md
- Jenkins Docs:
    - Building Jenkins: Building_Jenkins_github_repo.md
    - Creating Jenkins Node on LXC: Creating_Jenkins_Node_on_LXC.md
    - Creating a pipeline project: Creating_CI_CD_pipeline.md
    - Creating Multinode pipelines: Multinode_Pipelines.md
    - Adding custom-build packages in Jenkins: Adding_Custom-build_packages_in_Jenkins.md  
    - Github Push webhook integration: jenkins_github_integration/Github_push_webhook.md
    - Github PR webhook integration: jenkins_github_integration/Github_PR_webhook_integration.md
- QEMU and Linux Kernel:
    - Building Linux kernel and booting on QEMU: Building_Linux_Kernel.md
- Cross-Compilation:
    - Overview: Cross_Compiling/Overview.md
    - Installing qemu-riscv64: Cross_Compiling/Installing_qemu-riscv64.md
    - Cross Compiling Openssl: Cross_Compiling/Cross_compiling_openssl.md
    - Cross Compiling Ruby: Cross_Compiling/Cross_compiling_ruby.md
    - Cross Compiling Drhystone: Cross_Compiling/Cross_compiling_dhrystone.md
    - Cross Compiling Coremark: Cross_Compiling/Cross_compiling_coremark
- RISC-V CI User's Guide:
    - Guide for Software Developer: Software_Developer_Guide.md
theme: readthedocs
